--------------------------------------------------------------------------------
2016-12-07 21:01:43 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.Data.SqlClient.SqlException message is as follows: 

	Database 'LivFitNew20160819113218_db' on server 'livfitnew20160819113218dbserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{F74DEDE5-E8B7-4056-A923-C4DEC7B41E39}'.

	DBMS native error code: 1

--------------------------------------------------------------------------------
2016-12-07 21:01:55 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.InvalidOperationException message is as follows: 

	Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.


--------------------------------------------------------------------------------
2016-12-07 21:01:55 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.InvalidOperationException message is as follows: 

	Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.


--------------------------------------------------------------------------------
2016-12-07 21:02:02 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.InvalidOperationException message is as follows: 

	Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.


--------------------------------------------------------------------------------
2016-12-07 21:02:04 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.Data.SqlClient.SqlException message is as follows: 

	Database 'LivFitNew20160819113218_db' on server 'livfitnew20160819113218dbserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{57DC296B-E5FB-466E-B476-BA5ED2F334E8}'.

	DBMS native error code: 1

--------------------------------------------------------------------------------
2016-12-07 21:02:24 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.Data.SqlClient.SqlException message is as follows: 

	Database 'LivFitNew20160819113218_db' on server 'livfitnew20160819113218dbserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{50262587-EEDA-469A-BFAA-8640ADA50780}'.

	DBMS native error code: 1

--------------------------------------------------------------------------------
2016-12-07 21:02:33 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.InvalidOperationException message is as follows: 

	Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.


--------------------------------------------------------------------------------
2016-12-07 21:02:45 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.Data.SqlClient.SqlException message is as follows: 

	Database 'LivFitNew20160819113218_db' on server 'livfitnew20160819113218dbserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{BF1C83A7-9847-408D-B710-AB05F0BFAB66}'.

	DBMS native error code: 1

--------------------------------------------------------------------------------
2016-12-07 21:52:23 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.Data.SqlClient.SqlException message is as follows: 

	Database 'LivFitNew20160819113218_db' on server 'livfitnew20160819113218dbserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{95935779-9A31-447C-AED5-14B1DB92FC08}'.

	DBMS native error code: 1

--------------------------------------------------------------------------------
2016-12-07 21:53:02 DATABASE ACCESS ERROR

1) Database object's method Open reports the following: Open failed

2) The method call in your program is as follows:

	Open("Server=tcp:livfitnew20160819113218dbserver.database.windows.net,1433;Database=LivFitNew20160819113218_db;User ID=LivFitAdmin@livfitnew20160819113218dbserver;Password=Bnje5143;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;")

3) System.Data.SqlClient.SqlException message is as follows: 

	Database 'LivFitNew20160819113218_db' on server 'livfitnew20160819113218dbserver' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{9561FABD-1FA2-455C-A1C0-62C935C9F8EF}'.

	DBMS native error code: 1

